### ISSUE TITLE
Error using example.py

### ISSUE THREAD

**Issue by firewiremb** [Thomas55555/aioautomower#147]
Hi Thomas, when using example.py I get the following error:

```
>>> %Run automower_example.py
Mowers data: {}
Token expires at:  1704220269
Traceback (most recent call last):
  File "/home/bem/Dropbox/__Permanent__/Python/automower/automower_example.py", line 76, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
  File "/home/bem/Dropbox/__Permanent__/Python/automower/automower_example.py", line 65, in main
    await automower_api.connect()
  File "/home/bem/.env/lib/python3.11/site-packages/aioautomower/session.py", line 108, in connect
    await self.get_status()
  File "/home/bem/.env/lib/python3.11/site-packages/aioautomower/session.py", line 174, in get_status
    self.mower_as_dict_dataclass()
  File "/home/bem/.env/lib/python3.11/site-packages/aioautomower/session.py", line 331, in mower_as_dict_dataclass
    mowers_list = MowerList(**self._data)
  File "/home/bem/.env/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MowerList
data.0.attributes.workAreas
  Input should be a valid dictionary or instance of WorkAreas [type=model_type, input_value=[{'workAreaId': 14812, 'n...', 'cuttingHeight': 75}], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
```
What am I doing wrong?

**Comment by Thomas55555** [comment]
Probably nothing.
Can you change line 183 in `model.py` like here: https://github.com/Thomas55555/aioautomower/pull/148/commits/fc47f6cf039214a8922e8b52152fcadfba937225
and run again?

**Comment by firewiremb** [comment]
I changed the line accordingly. It works now. Many thanks for the quick response.
