### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by Kolbi** [Thomas55555/aioautomower#280]
> 2024-04-24 10:59:19.625 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
> await self._async_refresh(log_failures=True, scheduled=True)
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 416, in _async_refresh
> self.async_update_listeners()
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
> update_callback()
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 494, in _handle_coordinator_update
> self.async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
> state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in __async_calculate_state
> state = self._stringify_state(available)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in _stringify_state
> if (state := self.state) is None:
> ^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 548, in state
> value = self.native_value
> ^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/husqvarna_automower/sensor.py", line 179, in native_value
> return self.entity_description.value_fn(self.mower_attributes)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/husqvarna_automower/sensor.py", line 142, in <lambda>
> value_fn=lambda data: dt_util.as_local(data.planner.next_start_datetime),
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/util/dt.py", line 139, in as_local
> if dattim.tzinfo == DEFAULT_TIME_ZONE:
> ^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'tzinfo'

**Comment by Kolbi** [comment]
> 2024-04-24 11:03:58.587 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback AutomowerDataUpdateCoordinator.callback({'51f29104-950...-07ffd0b1ae42': MowerAttribut...g_height=49)}), 'd3996f27-ecb...-95b7946a6049': MowerAttribut...g_height=49)})})
> Traceback (most recent call last):
> File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
> self._context.run(self._callback, *self._args)
> File "/usr/src/homeassistant/homeassistant/components/husqvarna_automower/coordinator.py", line 52, in callback
> self.async_set_updated_data(ws_data)
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 452, in async_set_updated_data
> self.async_update_listeners()
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
> update_callback()
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 494, in _handle_coordinator_update
> self.async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
> state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in __async_calculate_state
> state = self._stringify_state(available)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in _stringify_state
> if (state := self.state) is None:
> ^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 548, in state
> value = self.native_value
> ^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/husqvarna_automower/sensor.py", line 179, in native_value
> return self.entity_description.value_fn(self.mower_attributes)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/husqvarna_automower/sensor.py", line 142, in <lambda>
> value_fn=lambda data: dt_util.as_local(data.planner.next_start_datetime),
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/util/dt.py", line 139, in as_local
> if dattim.tzinfo == DEFAULT_TIME_ZONE:
> ^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'tzinfo'
> 2024-04-24 11:03:58.594 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback AutomowerDataUpdateCoordinator.callback({'51f29104-950...-07ffd0b1ae42': MowerAttribut...g_height=49)}), 'd3996f27-ecb...-95b7946a6049': MowerAttribut...g_height=49)})})
> Traceback (most recent call last):
> File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
> self._context.run(self._callback, *self._args)
> File "/usr/src/homeassistant/homeassistant/components/husqvarna_automower/coordinator.py", line 52, in callback
> self.async_set_updated_data(ws_data)
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 452, in async_set_updated_data
> self.async_update_listeners()
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
> update_callback()
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 494, in _handle_coordinator_update
> self.async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
> state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in __async_calculate_state
> state = self._stringify_state(available)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in _stringify_state
> if (state := self.state) is None:
> ^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 548, in state
> value = self.native_value
> ^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/husqvarna_automower/sensor.py", line 179, in native_value
> return self.entity_description.value_fn(self.mower_attributes)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/components/husqvarna_automower/sensor.py", line 142, in <lambda>
> value_fn=lambda data: dt_util.as_local(data.planner.next_start_datetime),
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/src/homeassistant/homeassistant/util/dt.py", line 139, in as_local
> if dattim.tzinfo == DEFAULT_TIME_ZONE:
> ^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'tzinfo'
